[application]

# App (Project) Name
name = "prof-spoon"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
#out_dir = "dist"
out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

base_path = "prof-spoon"

# HTML title tag content
title = "prof-spoon"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets", "public"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["https://cdn.tailwindcss.com"]

# Javascript code file
script = ["https://cdn.tailwindcss.com"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
style = ["https://cdn.tailwindcss.com"]

# Javascript code file
script = ["https://cdn.tailwindcss.com"]
